apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: asai-x-bot
  annotations:
    run.googleapis.com/ingress: none # 外部からのアクセスを無効化
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
        # 15分のタイムアウト（X APIの制限に合わせて）
        run.googleapis.com/timeout: "900s"
    spec:
      containerConcurrency: 1
      timeoutSeconds: 900
      containers:
      - image: gcr.io/PROJECT_ID/asai-x-bot:latest
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
        env:
        - name: X_BEARER_TOKEN
          valueFrom:
            secretKeyRef:
              name: asai-x-bot-secrets
              key: X_BEARER_TOKEN
        - name: DISCORD_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: asai-x-bot-secrets
              key: DISCORD_WEBHOOK_URL
        - name: QUERY
          value: "(#浅井恋乃未) (from:sakurazaka46 OR from:sakura_joqr OR from:anan_mag OR from:Lemino_official)"
        - name: SINCE_ID_FILE
          value: "/tmp/data/since_id.txt"
