# Ruffで統一されたlinting/formatting設定

[tool.bandit]
exclude_dirs = ["tests"]
skips = ["B101"]  # Skip assert_used test

[tool.coverage.run]
source = ["src"]
omit = [
    "*/tests/*",
    "*/test_*",
    "*/__pycache__/*"
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "if settings.DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:"
]

[tool.ruff]
target-version = "py312"
line-length = 127
exclude = [
    ".git",
    ".pytest_cache",
    ".ruff_cache",
    "__pycache__",
    "build",
    "dist",
    "venv",
]

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # import sorting
    "B",   # bugbear
    "C4",  # comprehensions
    "UP",  # pyupgrade
    "N",   # pep8-naming
    "S",   # bandit (security)
    "T20", # print statements
    "PT",  # pytest-style
    "Q",   # quotes
    "RET", # return statements
    "SIM", # simplify
    "TID", # tidy-imports
    "ARG", # unused-arguments
    "ERA", # eradicate (commented code)
    "PL",  # pylint
    "TRY", # tryceratops
]
ignore = [
    "E501",  # line too long (handled by formatter)
    "B008",  # do not perform function calls in argument defaults
    "C901",  # too complex
    "S101",  # use of assert (OK in tests)
    "S104",  # hardcoded bind all interfaces (OK for Cloud Run)
    "S105",  # hardcoded password (handled by nosec comments)
    "PLR0913", # too many arguments
    "PLR2004", # magic value used in comparison
    "TRY003",  # avoid specifying messages outside exception class
    "TRY300",  # consider moving to else block
    "PT009",   # use regular assert
    "ERA001",  # commented-out code (some comments are intentional)
    "PLC0415", # import outside toplevel (OK for tests)
    "SIM117",  # combine with statements (sometimes clearer separately)
    "ARG002",  # unused method argument (OK for test fixtures)
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint.isort]
known-first-party = ["src"]
